create table if not exists players (
  id bigint generated by default as identity primary key,
  player_id text not null unique,
  player_id_norm text not null unique,
  name text not null,
  name_norm text not null,
  pin_salt text not null,
  pin_hash text not null,
  friend_code text not null unique,
  level integer not null default 1,
  exp integer not null default 0,
  rating integer not null default 1500,
  pin_fail_count integer not null default 0,
  pin_locked_until bigint not null default 0,
  created_at bigint not null,
  updated_at bigint not null,
  last_login_at bigint
);

create index if not exists players_name_norm_idx on players (name_norm);
create index if not exists players_friend_code_idx on players (friend_code);

create table if not exists auth_sessions (
  token text primary key,
  player_id bigint not null references players(id) on delete cascade,
  created_at bigint not null,
  last_seen_at bigint not null,
  expires_at bigint not null,
  device_label text
);

create index if not exists auth_sessions_player_id_idx on auth_sessions (player_id);

create table if not exists friend_requests (
  id bigint generated by default as identity primary key,
  sender_player_id bigint not null references players(id) on delete cascade,
  receiver_player_id bigint not null references players(id) on delete cascade,
  status text not null default 'pending',
  created_at bigint not null,
  responded_at bigint,
  unique (sender_player_id, receiver_player_id)
);

create index if not exists friend_requests_sender_idx on friend_requests (sender_player_id);
create index if not exists friend_requests_receiver_idx on friend_requests (receiver_player_id);

create table if not exists friends (
  player1_id bigint not null references players(id) on delete cascade,
  player2_id bigint not null references players(id) on delete cascade,
  created_at bigint not null,
  primary key (player1_id, player2_id)
);

create index if not exists friends_player1_idx on friends (player1_id);
create index if not exists friends_player2_idx on friends (player2_id);

create table if not exists match_history (
  id bigint generated by default as identity primary key,
  match_key text unique,
  player1_id bigint references players(id) on delete cascade,
  player2_id bigint references players(id) on delete cascade,
  player1_name text not null,
  player2_name text not null,
  winner text not null,
  loser text not null,
  result text not null,
  player1_get_rating integer not null,
  player2_get_rating integer not null,
  player1_level integer not null,
  player2_level integer not null,
  started_time bigint not null,
  ended_time bigint not null,
  time_taken bigint not null,
  surrender_by_player_id bigint references players(id) on delete set null,
  created_at bigint not null
);

create index if not exists match_history_player1_idx on match_history (player1_id);
create index if not exists match_history_player2_idx on match_history (player2_id);
create index if not exists match_history_started_time_idx on match_history (started_time desc);
